### PR TITLE
Stop testing with ansible devel on py38

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by apatard** [comment]
I've been tempted to do that in the past. Sometimes the CI is getting failures due to unrelated change in -devel and it's getting in our way. On the other side, knowing in advance that some change in next molecule version will break something is useful.

So, I'm not sure what to do or if there's an easy way to get regular -devel testing against main branch but not on PR.

**Comment by apatard** [comment]
> @apatard You can set the test to be optional, so it runs on PR. Or you can even set it to only run when branch is master and set up a cron trigger for it. Then it won't block merges but can still yield useful warnings.

There's already a job schedule for the tox job, so the point is more to run the -devel check the way you're suggesting. I'll have to check the gha doc on how to do that. Unless @ssbarnea has time to update this PR to do it ?
(unrelated side note: I'm not getting the mails from the schedules for molecule-vagrant but that's a different matter)

**Comment by ssbarnea** [comment]
OOps, you are right. that devel of molecule and not devel of ansible. Yep, we need to keep at least one running. I will update it.

**Comment by ssbarnea** [comment]
At least my change proved that the issue was originating from devel and not previous release as tests passed.

**Comment by greg-hellings** [comment]
You should be able to filter based on a `if` clause, only running the `-devel` tests when branch is equal to main. I know all of that information is passed through in the contexts, you'd just have to string together the proper conditional bits in the job workflow.

**Comment by apatard** [comment]
@ssbarnea Looks like that neither of us had time to update this PR to run testing with molecule devel only on main and not merge. Should this PR be closed ?

**Pull request merged**
