### PR TITLE
BLD: setup.cfg: install_requires ansible

### PR DESCRIPTION
**Pull request by westurner**

### CODE REVIEW

**Comment by hswong3i** [comment]
Fixed by https://github.com/ansible-community/molecule-vagrant/commit/5e6d51bf8236038201d2c41f57c8d528e5f4351a

**Comment by dhoer** [comment]
@ssbarnea Can this please be released?  Molecule 3 is released and that requires this module in order to test via vagrant.   Which the current release is broken.  

Also, is there plans to update molecule's read the docs on adding drivers?  I took a while to figure out that there is actual support for vagrant in 3.x molecule.

**Comment by hswong3i** [comment]
@dhoer Please refer to https://github.com/ansible-community/molecule-vagrant/issues/8#issuecomment-589741665 for install from master

**Comment by stdevel** [comment]
Thanks for pointing out the workaround, @hswong3i - anyhow I'm looking forward for a persistent fix. :)

**Comment by ssbarnea** [comment]
No longer applies.

**Pull request closed without merging**
