### PR TITLE
Enable testing with ubuntu-bionic

### PR DESCRIPTION
**Pull request by ssbarnea**
Also exposes Ubuntu as a supported platform.

### CODE REVIEW

**Comment by apatard** [comment]
@ssbarnea what's the status about this ? Am I remembering correctly that the failure was related to a missing ``meta: reset_connection`` or something like that, preventing the test user to get added into the ``libvirt`` group ?

**Comment by apatard** [comment]
newgrp is starting a subshell so it's useless. Changing the libvirtd configuration to rely on polkit instead of unix rights seems a better solution. It's working exactly like unix rights, except that it's reading the group information when asked, so no need to login/logout.
A diff  for that is looking like: https://gist.github.com/apatard/61c39a684c5d7eaff35d89a43104bd3c

Briefly tested on fedora/centos/bionic.

**Comment by apatard** [comment]
recheck

**Comment by apatard** [comment]
recheck

**Comment by apatard** [comment]
recheck

**Comment by apatard** [comment]
recheck

**Comment by ssbarnea** [comment]
recheck

**Pull request merged**
