### PR TITLE
Make cachier optional

### LINKED ISSUE #100: Add option to disable vagrant-cachier
Currently the generated Vagrantfile checks for the presence of the cachier plugin, and configures it if it is found.

However, it's very possible that this plugin could be installed on some hosts, but not others, and a user might want to explicitly disable this. Provide an option to allow that.

### PR DESCRIPTION
**Pull request by greg-hellings**
Fixes #100

### CODE REVIEW

**Comment by greg-hellings** [comment]
I've rebased this on top of #102 so that we can see test results here.

**Review by apatard — COMMENTED** [review]
As said in https://github.com/ansible-community/molecule-vagrant/issues/100#issuecomment-823047934, I'm worried about the maintainance of vagrant-cachier. So, maybe disable cachier by default would be a thing but this may possibly **silently** break things for users :(
At least, with this PR, things remains the same, while allowing to disable cachier.

**Comment by greg-hellings** [comment]
Cachier still works for me. It's not getting knowledge of new package types, obviously, but I haven't had any issues with it.

**Comment by greg-hellings** [comment]
I can't see the logs from the ansible/check failures, but I'm happy to address them if I can.

**Comment by apatard** [comment]
The check failure is on zuul and it was a timeout and I bet it was some kind of "glitch" so nothing to do except running the checks again to see if it happens again

**Comment by apatard** [comment]
> Cachier still works for me. It's not getting knowledge of new package types, obviously, but I haven't had any issues with it.

ok. nice. So, if it's still working, I'm happy with the current PR, as long as the checks are happy too

**Comment by apatard** [comment]
recheck

**Comment by apatard** [comment]
recheck

**Comment by greg-hellings** [comment]
This time the Ubuntu test passed, but the linter timed out. Resource contention issues? :laughing:

**Comment by ssbarnea** [comment]
I would call it zuul-gambling... let me remove the linters at least, two failures in a single day is far more than I am willing to deal with.

**Pull request merged**
