### PR TITLE
Fix multi-host provisioning

### PR DESCRIPTION
**Pull request by apatard**
This patchset is fixing multiplatform support. Until now, when multiple instances are declared, the ``create.yml`` playbook is looping over the instance list and calls the vagrant module. This leads to one ``Vagrantfile`` per instance which are overwritten at each step of the loop.
This make debugging harder and - in some cases - may confuse vagrant.
This patchset is allowing to directly give ``molecule.yml`` instances list to the vagrant module and then the module is producing a proper ``Vagrantfile``.

### CODE REVIEW

**Comment by apatard** [comment]
recheck

**Comment by sio** [comment]
Vagrant Cloud is broken at the moment, these CI failures are not because of your changes: https://github.com/hashicorp/vagrant/issues/12390

**Comment by apatard** [comment]
@sio oh... Thanks for the info. I will refrain me from sending new PR or recheck then.

**Comment by sio** [comment]
I didn't mean to dissuade you from submitting new PRs, I was just letting you know that CI will not be functional for some time due to upstream service provider outage :)

It took me quite some time this morning to understand that the problem is not on my end and I wanted to save you the same trouble.

**Comment by apatard** [comment]
hm. weird. Probably not related to this PR but ...
```
2021-05-26T07:59:49.8041450Z TASK [Bootstrap python for Ansible] ********************************************
2021-05-26T07:59:49.8151860Z Wednesday 26 May 2021  07:59:49 +0000 (0:00:00.065)       0:00:00.065 *********
2021-05-26T08:00:06.3782880Z [32mok: [instance][0m
```
So the prepare.yml did install python but
```
2021-05-26T08:00:08.6030260Z TASK [sample task] *************************************************************
2021-05-26T08:00:08.6045050Z Wednesday 26 May 2021  08:00:08 +0000 (0:00:00.039)       0:00:00.039 *********
2021-05-26T08:00:09.4077040Z [1;35m[WARNING]: No python interpreters found for host instance (tried[0m
2021-05-26T08:00:09.4098840Z [1;35m['/usr/bin/python', 'python3.9', 'python3.8', 'python3.7', 'python3.6',[0m
2021-05-26T08:00:09.4157470Z [1;35m'python3.5', 'python2.7', 'python2.6', '/usr/libexec/platform-python',[0m
2021-05-26T08:00:09.4160370Z [1;35m'/usr/bin/python3', 'python'])[0m
2021-05-26T08:00:09.4163550Z [31mfatal: [instance]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python: not found\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}[0m
2021-05-26T08:00:09.4165610Z
```
Given that the scenario is the default configuration, aka:
```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
provisioner:
  name: ansible
```
I'm not convinced that setting the box to use the test one is a good idea....

**Review by Yajo — APPROVED** [review]
I've been testing this PR in my local dev workflow.

Without it, I was almost about to dump molecule-vagrant. It became too complicated.

With it, it works like a charm. VMs spin up faster. If I need to debug anything or connect to one of them, I just have to `cd` to the scenario ephemeral directory and run `vagrant ssh server0`.

Non-deep code review looks good also.

Thanks! This is a must have. 😃

**Comment by apatard** [comment]
> With it, it works like a charm. VMs spin up faster. If I need to debug anything or connect to one of them, I just have to `cd` to the scenario ephemeral directory and run `vagrant ssh server0`.

hm. `molecule login` is not working for you ?

**Comment by Yajo** [comment]
> hm. `molecule login` is not working for you ?

I didn't know it existed 😅 

It's working great!

**Comment by Yajo** [comment]
In any case, I still think this different approach is a good enhancement. It is more similar to what one would do if not using molecule, and is faster.

One problem I noticed is that, when using this PR, machines were created without a network interface.

When using a4bd8b1, they got created with networking.

My platforms definition is:

```yaml
platforms:
  - &server
    box: generic/ubuntu2004
    groups:
      - k8s_server
      - k8s_node
    name: server0
  - <<: *server
    name: server1
  - <<: *server
    name: server2
```

**Comment by apatard** [comment]
@Yajo Networking should work. Can you share your molecule.yml so that I can try to reproduce and fix over the week ? It would be bad to see this PR merged if there's a know bug...

**Comment by Yajo** [comment]
Here it is:

```yaml
dependency:
  # name: galaxy
  # options:
  #   role-file: requirements.yaml
  #   requirements-file: requirements.yaml
  name: shell
  command: ansible-galaxy install -r requirements.yaml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - &server
    box: generic/ubuntu2004
    groups:
      - k8s_server
      - k8s_node
    name: server0
  - <<: *server
    name: server1
  - <<: *server
    name: server2
provisioner:
  name: ansible
  connection_options:
    ansible_become: true
  config_options:
    defaults:
      vault_password_file: ${MOLECULE_PROJECT_DIRECTORY}/.vault_password.txt
  inventory:
    links:
      group_vars: ../../group_vars
verifier:
  name: ansible
```

**Comment by apatard** [comment]
@Yajo tried quickly your setup and I can use ``molecule login`` to connect so the network seems to work. Can you have a look at the vagrant .err and .out log files  to see if there's a clue ?

**Comment by Yajo** [comment]
It seems related to using `libvirt.qemu_use_session = true` which seems to have some problems on creating network interfaces.

**Comment by Yajo** [comment]
Definitely the issues I'm experiencing are lower in the stack. Check https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1342 if you're interested. But nothing related to this PR.

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
